import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useInView } from "motion/react";
import { ArrowUpRight, Check, ChevronDown, Code2, Gauge, Megaphone, PenTool, Search, ShoppingBag, Star } from "lucide-react";
import hotelImage from "../../assets/hotel-project.jpg";
import { brand, faqs, processSteps, services, team, testimonials } from "./content";
import { MagneticLink, Reveal, SectionHeading } from "./MotionKit";

const icons = { Code2, Gauge, Megaphone, PenTool, Search, ShoppingBag };
const reasons = ["Custom-built websites", "Modern design", "Mobile-first development", "Fast performance", "SEO-ready structure", "Transparent communication", "Long-term support", "Digital marketing expertise"];
const technologies = ["Next.js", "React", "JavaScript", "Node.js", "Express", "MongoDB", "MySQL", "Tailwind CSS", "Motion", "GitHub", "SEO", "Analytics"];

function Counter({ value }) { const ref=useRef(null); const visible=useInView(ref,{once:true}); const [count,setCount]=useState(0); useEffect(()=>{if(!visible)return; let frame=0; const timer=setInterval(()=>{frame+=1;setCount(Math.round(value*frame/35));if(frame===35)clearInterval(timer)},32);return()=>clearInterval(timer)},[visible,value]); return <span ref={ref}>{count}+</span>; }

export function Marquee() { const items=["Website Development","Digital Marketing","SEO","Branding","UI/UX","E-Commerce","Custom Software"]; return <section className="trust-strip"><p>Built for businesses that want to be taken seriously online.</p><div className="marquee"><div>{[...items,...items].map((x,i)=><span key={`${x}-${i}`}><i />{x}</span>)}</div></div></section>; }

export function About() { return <section className="section about-section" id="about"><div className="section-shell about-grid"><div><p className="eyebrow">01 / About the studio</p><h2 className="display-title">Small team.<br/><em>Big digital</em><br/>ambition.</h2></div><div className="about-copy"><Reveal><p className="lead">We are a focused team of developers and digital marketing professionals helping businesses build a stronger presence online.</p></Reveal><Reveal><p>Strategy, design, technology and marketing live together here. That means fewer handoffs, clearer thinking and digital work that is built around the whole business—not only the screen.</p></Reveal><div className="big-number"><span>04</span><p>Team members<br/><small>One focused unit</small></p></div></div></div></section>; }

export function Services() { return <section className="section services-section" id="services"><div className="section-shell"><SectionHeading kicker="02 / Capabilities">What we do</SectionHeading><div className="services-list">{services.map((service,i)=>{const Icon=icons[service.icon];return <motion.article className="service-row" key={service.title} initial="rest" whileHover="hover"><span>0{i+1}</span><motion.h3 variants={{hover:{x:12}}}>{service.title}</motion.h3><p>{service.text}</p><motion.div className="service-icon" variants={{hover:{rotate:8,scale:1.1}}}><Icon/></motion.div></motion.article>})}</div></div></section>; }

export function WhyUs() { return <section className="section why-section"><div className="section-shell why-grid"><SectionHeading kicker="Built with intent">Why businesses<br/>choose us</SectionHeading><div className="reason-list">{reasons.map((r,i)=><Reveal key={r}><div className="reason"><span>0{i+1}</span><p>{r}</p><Check size={19}/></div></Reveal>)}</div></div><div className="stats-row">{[[20,"Projects"],[15,"Happy clients"],[4,"Team members"],[3,"Years experience"]].map(([n,l])=><div key={l}><Counter value={n}/><p>{l}</p></div>)}</div></section>; }

export function HotelDemo() { return <section className="section hotel-section"><div className="section-shell"><SectionHeading kicker="Hospitality focus">Your business deserves more than a Google listing.</SectionHeading><p className="hotel-intro">We help hotels, restaurants and local businesses turn their online presence into a professional digital experience.</p><div className="hotel-showcase"><img src={hotelImage} alt="Fictional luxury hotel website concept shown on screen" loading="lazy" width="1600" height="1000"/><div className="hotel-browser"><div className="browser-bar"><span/><span/><span/></div><p>AURELIA / RETREAT</p><h3>Stay somewhere<br/><em>worth remembering.</em></h3><button type="button">Book your stay <ArrowUpRight size={15}/></button></div><div className="hotel-features">{["Direct booking","Immersive gallery","Guest reviews","Restaurant","Location","WhatsApp enquiry"].map(x=><span key={x}><Check size={14}/>{x}</span>)}</div></div><MagneticLink href="#contact">Build my business website</MagneticLink></div></section>; }

export function Process() { return <section className="section process-section" id="process"><div className="section-shell"><SectionHeading kicker="04 / Our process">From idea to launch</SectionHeading><div className="process-line">{processSteps.map(([title,text],i)=><Reveal className="process-step" key={title}><span>0{i+1}</span><i/><h3>{title}</h3><p>{text}</p></Reveal>)}</div></div></section>; }

export function TeamAndTech() { return <><section className="section team-section"><div className="section-shell"><SectionHeading kicker="05 / The studio">The people behind the pixels</SectionHeading><p className="demo-note">Team details are placeholders and ready to be replaced.</p><div className="team-grid">{team.map(([name,role],i)=><article className="team-card" key={name}><div className={`team-portrait portrait-${i+1}`}><span>{String(i+1).padStart(2,"0")}</span></div><p>{name}</p><h3>{role}</h3></article>)}</div></div></section><section className="tech-section"><div className="section-shell tech-grid"><div><p className="eyebrow">Technology ecosystem</p><h2 className="section-title">Modern tools.<br/>Practical outcomes.</h2></div><div className="tech-orbit">{technologies.map((t,i)=><motion.span key={t} className={`tech-pill pill-${i%4}`} animate={{y:[0,-8,0]}} transition={{duration:3+i%3,repeat:Infinity,ease:"easeInOut",delay:i*.12}}>{t}</motion.span>)}</div></div></section></>; }

export function Testimonials() { const [active,setActive]=useState(0); useEffect(()=>{const t=setInterval(()=>setActive(a=>(a+1)%testimonials.length),5000);return()=>clearInterval(t)},[]); return <section className="section testimonial-section"><div className="section-shell"><p className="eyebrow">Demo testimonials / layout preview</p><div className="testimonial-stage"><span className="quote-mark">“</span><AnimatePresence mode="wait"><motion.blockquote key={active} initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} transition={{duration:.45}}><p>{testimonials[active][0]}</p><footer>{testimonials[active][1]}</footer></motion.blockquote></AnimatePresence><div className="testimonial-dots">{testimonials.map((_,i)=><button key={i} onClick={()=>setActive(i)} className={active===i?"active":""} aria-label={`View demo testimonial ${i+1}`}/>)}</div></div></div></section>; }

export function FAQ() { const [open,setOpen]=useState(0); return <section className="section faq-section"><div className="section-shell faq-grid"><SectionHeading kicker="Questions, answered">Good to know.</SectionHeading><div>{faqs.map(([q,a],i)=><article className="faq-item" key={q}><button onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><span>{q}</span><motion.span animate={{rotate:open===i?180:0}}><ChevronDown/></motion.span></button><AnimatePresence initial={false}>{open===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p>{a}</p></motion.div>}</AnimatePresence></article>)}</div></div></section>; }

export function FinalCTA() { return <section className="final-cta"><div className="cta-light"/><div className="section-shell"><p className="eyebrow">Ready when you are</p><h2>Your next customer is already <em>searching for you.</em></h2><p>Let's build a digital presence that earns attention, builds trust and turns visitors into customers.</p><div><MagneticLink href="#contact">Start a project</MagneticLink><MagneticLink href={brand.whatsapp} secondary external>Talk on WhatsApp</MagneticLink></div></div></section>; }

export function Contact() { const [sent,setSent]=useState(false); return <section className="section contact-section" id="contact"><div className="section-shell contact-grid"><div><SectionHeading kicker="Start a conversation">Let's build something valuable.</SectionHeading><div className="contact-info"><a href={`mailto:${brand.email}`}>{brand.email}</a><a href={brand.whatsapp}>{brand.phone}</a><p>{brand.location}</p></div><div className="socials"><a href="#contact">Instagram</a><a href="#contact">LinkedIn</a><a href={brand.whatsapp}>WhatsApp</a></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}>{[["Name","text"],["Business name","text"],["Phone","tel"],["Email","email"]].map(([label,type])=><label key={label}><span>{label}</span><input type={type} required placeholder={label}/></label>)}<label><span>Business type</span><input placeholder="Hotel, restaurant, startup..."/></label><label><span>Services required</span><select defaultValue=""><option value="" disabled>Select a service</option>{["Website","E-Commerce","Digital Marketing","SEO","Redesign","Other"].map(x=><option key={x}>{x}</option>)}</select></label><label className="full-field"><span>Tell us about the project</span><textarea rows="4" placeholder="Goals, timeline, current challenges..."/></label><button className="submit-button" type="submit">{sent?"Enquiry ready — we'll be in touch":"Send enquiry"}<ArrowUpRight/></button>{sent&&<p className="form-note">Demo form complete. Connect your preferred inbox before launch.</p>}</form></div></section>; }